<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6828de49ea89ce9a4763c25511869971
{
    public static $classMap = array (
        'Baraja\\PdfToImage\\Convertor' => __DIR__ . '/..' . '/baraja-core/php-pdf-to-image/src/Convertor.php',
        'Baraja\\PdfToImage\\ConvertorException' => __DIR__ . '/..' . '/baraja-core/php-pdf-to-image/src/ConvertorException.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit6828de49ea89ce9a4763c25511869971::$classMap;

        }, null, ClassLoader::class);
    }
}
