<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Baraja\\PdfToImage\\Convertor' => $vendorDir . '/baraja-core/php-pdf-to-image/src/Convertor.php',
    'Baraja\\PdfToImage\\ConvertorException' => $vendorDir . '/baraja-core/php-pdf-to-image/src/ConvertorException.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
